### ISSUE TITLE
Project segment bug: traces beyond the segment length do not get saved.

### ISSUE THREAD

**Issue by jpcrypt** [newaetech/chipwhisperer#254] opened 2020-01-29 16:03 UTC
When adding traces to a project with `project.traces.append()`, traces beyond the default segment length of 10000 will not get saved.
After 10000 traces a new segment is created, but in the .cwp project file, the new .cfg is the same as the previous one:
```
Trace Management]
tracefile0 = Tutorial_HW_CW305_lots_traces_data\traces\config_2020.01.29-09.38.03_.cfg
enabled0 = True
tracefile1 = Tutorial_HW_CW305_lots_traces_data\traces\config_2020.01.29-09.38.03_.cfg
enabled1 = True
```
Unfortunately, `len(project.traces)` suggests that all traces are there, but `project.traces[x]` is the same as `project.traces[x+10000]`.

A temporary workaround is to increase the segment length to the number of traces one wants to capture, for example:
```
project.traces.seg_len = 30000
project.traces.seg_ind_max = project.traces.seg_len-1
```
However this is not ideal and can degrade performance.

**Comment by alex-dewar** [comment] 2020-02-10 20:03
Alright, so this seems to be caused by the file name for the traces not being updated when save method cycles through the segments. It should be fixed in the latest commit.

**Closed** 2020-02-13 16:05 UTC
Labels: bug, cw5
