### ISSUE TITLE
openadc submodule link

### ISSUE THREAD

**Issue by colinoflynn** [newaetech/chipwhisperer#273] opened 2020-07-03 01:12 UTC
openadc submodule is pointing maybe to wrong version or something. https://app.assembla.com/spaces/openadc/git/source is still public but the link in the submodule is private.

**Comment by alex-dewar** [comment] 2020-08-31 14:38
Fixed by aafe800aa30ddc904641465f924cafe9162ec948 - was caused by a git:// link instead of an https:// one

**Closed by alex-dewar** 2020-08-31 14:38 UTC
